#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.21f1c1_7fef87dbc35f"
#define UNITY_VERSION_FULL_NICE "2019.4.21f1c1 (7fef87dbc35f)"
#define UNITY_VERSION_BLD 8384391
#define UNITY_VERSION_DATE 1613805042
#define UNITY_VERSION_WIN "2019.4.21.8384391"
#define UNITY_VERSION_BRANCH "2019.4/china_unity/release"
