#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2019.4.21f1c1"
#define UNITY_VERSION_DIGITS "2019.4.21"
#define UNITY_VERSION_SUFFIX "f1c1"
#define UNITY_VERSION_VER 2019
#define UNITY_VERSION_MAJ 4
#define UNITY_VERSION_MIN 21
#define UNITY_IS_BETA 0
